#!/usr/bin/env bash
# =============================================================================
# generate-env-docs.sh
# Stage 2b: Generate structured markdown documentation from exported ARM data.
# Idempotent: overwrites docs on each run (deterministic output).
# =============================================================================
set -euo pipefail

EXPORT_DIR=""
OUTPUT_DIR=""
RUN_ID=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --export-dir)  EXPORT_DIR="$2";  shift 2 ;;
    --output-dir)  OUTPUT_DIR="$2";  shift 2 ;;
    --run-id)      RUN_ID="$2";      shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

mkdir -p "${OUTPUT_DIR}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
DATE_DISPLAY=$(date -u +"%Y-%m-%d %H:%M UTC")

echo "============================================================"
echo "STAGE 2b: Generate Environment Documentation"
echo "  Run ID: ${RUN_ID}"
echo "  Output: ${OUTPUT_DIR}"
echo "============================================================"

# ── Helper: count resources by type from a resources.json ────────────────────
count_type() {
  local file="$1"
  local type_filter="$2"
  jq --arg t "$type_filter" '[.[] | select(.type | ascii_downcase | contains($t))] | length' "$file" 2>/dev/null || echo 0
}

# ── Main environment documentation ───────────────────────────────────────────
EXPORT_INDEX="${EXPORT_DIR}/export-index.json"
[[ ! -f "$EXPORT_INDEX" ]] && { echo "ERROR: export-index.json not found"; exit 1; }

# Build per-subscription docs
declare -A SUB_DOCS

while IFS= read -r entry; do
  sub_id=$(echo "$entry" | jq -r '.subscriptionId')
  rg_name=$(echo "$entry" | jq -r '.resourceGroup')
  rg_dir="${EXPORT_DIR}/arm-templates/${sub_id}/${rg_name}"

  resources_file="${rg_dir}/resources.json"
  [[ ! -f "$resources_file" ]] && continue

  vm_count=$(count_type "$resources_file" "microsoft.compute/virtualmachines")
  storage_count=$(count_type "$resources_file" "microsoft.storage/storageaccounts")
  vnet_count=$(count_type "$resources_file" "microsoft.network/virtualnetworks")
  keyvault_count=$(count_type "$resources_file" "microsoft.keyvault/vaults")
  total_count=$(jq 'length' "$resources_file")

  SUB_DOCS["$sub_id"]+="
### Resource Group: \`${rg_name}\`

| Category | Count |
|---|---|
| Total Resources | ${total_count} |
| Virtual Machines | ${vm_count} |
| Storage Accounts | ${storage_count} |
| Virtual Networks | ${vnet_count} |
| Key Vaults | ${keyvault_count} |

<details>
<summary>Resource List</summary>

\`\`\`json
$(jq '[.[] | {name, type, location}]' "$resources_file" 2>/dev/null | head -200)
\`\`\`

</details>
"
done < <(jq -c '.[]' "$EXPORT_INDEX")

# ── Write top-level environment doc ──────────────────────────────────────────
{
  echo "# Azure Environment Documentation"
  echo ""
  echo "> **Generated:** ${DATE_DISPLAY}  "
  echo "> **Pipeline Run:** \`${RUN_ID}\`  "
  echo "> **API Versions:** Resource Graph \`2024-04-01\` · ARM \`2021-04-01\`"
  echo ""
  echo "---"
  echo ""
  echo "## Table of Contents"
  echo ""
  for sub_id in "${!SUB_DOCS[@]}"; do
    echo "- [Subscription: ${sub_id}](#subscription-${sub_id//-/})"
  done
  echo ""
  echo "---"
  echo ""

  for sub_id in "${!SUB_DOCS[@]}"; do
    echo "## Subscription: \`${sub_id}\`"
    echo ""
    echo "${SUB_DOCS[$sub_id]}"
    echo ""
    echo "---"
    echo ""
  done

  echo "## Network Topology"
  echo ""

  # Pull VNet info from scan if available
  VNET_SCAN=""
  # Find vnet scan file by looking in possible locations
  for candidate in \
    "$(dirname "$EXPORT_DIR")/scan/vnets.json" \
    "${EXPORT_DIR}/../scan/vnets.json"; do
    [[ -f "$candidate" ]] && { VNET_SCAN="$candidate"; break; }
  done

  if [[ -n "$VNET_SCAN" ]]; then
    echo "| VNet Name | Resource Group | Location | Address Space |"
    echo "|---|---|---|---|"
    jq -r '.[] | [.name, .resourceGroup, .location, (.addressSpace.addressPrefixes // [] | join(", "))] | @tsv' \
      "$VNET_SCAN" 2>/dev/null | \
      while IFS=$'\t' read -r name rg loc addr; do
        echo "| ${name} | ${rg} | ${loc} | ${addr} |"
      done
  else
    echo "_VNet data not available in this run._"
  fi

  echo ""
  echo "---"
  echo ""
  echo "_This document is auto-generated by the Azure Compliance Pipeline._"
  echo "_Do not edit manually — changes will be overwritten on the next PR._"
} > "${OUTPUT_DIR}/ENVIRONMENT.md"

echo "INFO: Written ${OUTPUT_DIR}/ENVIRONMENT.md"

# ── Per-subscription JSON summary ─────────────────────────────────────────────
jq -c '.[]' "$EXPORT_INDEX" | while IFS= read -r entry; do
  sub_id=$(echo "$entry" | jq -r '.subscriptionId')
  mkdir -p "${OUTPUT_DIR}/${sub_id}"
  # Aggregate all resource groups for this subscription
  jq -n \
    --arg sub "$sub_id" \
    --arg ts "$TIMESTAMP" \
    --arg runId "$RUN_ID" \
    '{ subscriptionId: $sub, generatedAt: $ts, runId: $runId }' \
    > "${OUTPUT_DIR}/${sub_id}/summary.json"
done

echo ""
echo "============================================================"
echo "DOCS COMPLETE"
echo "  Output: ${OUTPUT_DIR}"
echo "============================================================"
