#Requires -Version 7.2
# =============================================================================
# generate-env-docs.ps1
# Stage 2b: Generate ENVIRONMENT.md from exported ARM/scan data.
# Idempotent: overwrites docs on each run (deterministic output).
# =============================================================================
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $ExportDir,
    [Parameter(Mandatory)] [string] $OutputDir,
    [Parameter(Mandatory)] [string] $RunId
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

$null        = New-Item -ItemType Directory -Force -Path $OutputDir
$Timestamp   = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$DateDisplay = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm UTC")

Write-Host "============================================================"
Write-Host "STAGE 2b: Generate Environment Documentation"
Write-Host "  Run ID: $RunId   Output: $OutputDir"
Write-Host "============================================================"

$IndexFile = Join-Path $ExportDir "export-index.json"
if (-not (Test-Path $IndexFile)) { Write-Error "export-index.json not found in $ExportDir"; exit 1 }
$Index = Get-Content $IndexFile -Raw | ConvertFrom-Json

# Group entries by subscription
$SubGroups = $Index | Group-Object -Property subscriptionId

# ── Build markdown ────────────────────────────────────────────────────────────
$Lines = [System.Collections.Generic.List[string]]::new()
$Lines.Add("# Azure Environment Documentation")
$Lines.Add("")
$Lines.Add("> **Generated:** $DateDisplay  ")
$Lines.Add("> **Pipeline Run:** ``$RunId``  ")
$Lines.Add("> **API Versions:** Resource Graph ``2024-04-01`` · ARM ``2021-04-01``")
$Lines.Add("")
$Lines.Add("---")
$Lines.Add("")
$Lines.Add("## Table of Contents")
$Lines.Add("")
foreach ($Grp in $SubGroups) {
    $Anchor = $Grp.Name -replace "-", ""
    $Lines.Add("- [Subscription: $($Grp.Name)](#subscription-$Anchor)")
}
$Lines.Add("")
$Lines.Add("---")
$Lines.Add("")

foreach ($Grp in $SubGroups) {
    $Lines.Add("## Subscription: ``$($Grp.Name)``")
    $Lines.Add("")

    foreach ($Entry in $Grp.Group) {
        $RgName      = $Entry.resourceGroup
        $ResourcesFile = Join-Path $ExportDir "arm-templates" $Grp.Name $RgName "resources.json"

        if (-not (Test-Path $ResourcesFile)) { continue }
        $Resources = Get-Content $ResourcesFile -Raw | ConvertFrom-Json

        $VmCount      = ($Resources | Where-Object { $_.type -like "*virtualMachines*" }).Count
        $StorageCount = ($Resources | Where-Object { $_.type -like "*storageAccounts*" }).Count
        $VnetCount    = ($Resources | Where-Object { $_.type -like "*virtualNetworks*" }).Count
        $KvCount      = ($Resources | Where-Object { $_.type -like "*vaults*" }).Count

        $Lines.Add("### Resource Group: ``$RgName``")
        $Lines.Add("")
        $Lines.Add("| Category | Count |")
        $Lines.Add("|---|---|")
        $Lines.Add("| Total Resources | $($Resources.Count) |")
        $Lines.Add("| Virtual Machines | $VmCount |")
        $Lines.Add("| Storage Accounts | $StorageCount |")
        $Lines.Add("| Virtual Networks | $VnetCount |")
        $Lines.Add("| Key Vaults | $KvCount |")
        $Lines.Add("")
    }
    $Lines.Add("---")
    $Lines.Add("")
}

# Network topology section
$Lines.Add("## Network Topology")
$Lines.Add("")
$VnetFile = Join-Path (Split-Path $ExportDir) "scan" "vnets.json"
if (Test-Path $VnetFile) {
    $Vnets = Get-Content $VnetFile -Raw | ConvertFrom-Json
    $Lines.Add("| VNet Name | Resource Group | Location | Address Space |")
    $Lines.Add("|---|---|---|---|")
    foreach ($Vnet in $Vnets) {
        $Addr = ($Vnet.addressSpace.addressPrefixes -join ", ")
        $Lines.Add("| $($Vnet.name) | $($Vnet.resourceGroup) | $($Vnet.location) | $Addr |")
    }
} else {
    $Lines.Add("_VNet data not available in this run._")
}

$Lines.Add("")
$Lines.Add("---")
$Lines.Add("")
$Lines.Add("_This document is auto-generated by the DRaaC Pipeline. Do not edit manually._")

$Lines | Set-Content (Join-Path $OutputDir "ENVIRONMENT.md") -Encoding UTF8
Write-Host "INFO: Written $(Join-Path $OutputDir 'ENVIRONMENT.md')"

# Per-subscription summaries
foreach ($Grp in $SubGroups) {
    $SubOutDir = Join-Path $OutputDir $Grp.Name
    $null = New-Item -ItemType Directory -Force -Path $SubOutDir
    [ordered]@{ subscriptionId = $Grp.Name; generatedAt = $Timestamp; runId = $RunId } |
        ConvertTo-Json | Set-Content (Join-Path $SubOutDir "summary.json") -Encoding UTF8
}

Write-Host "DOCS COMPLETE — Output: $OutputDir"
